# Used by Netlify for redirects. Lines with status code 200 are proxied and
# rewritten by Netlify.

# From the previous nginx.conf
[[redirects]]
  from = "/integration"
  to = "/howto/integration"
  status = 301

# The directory index is redirected to the new canonical location
[[redirects]]
  from = "/download"
  to = "https://sources.nginx.org/unit/"
  status = 301
  headers = {X-From = "Netlify"}

# To keep old download links alive, we proxy direct requests for specific files
[[redirects]]
  from = "/download/*"
  to = "https://sources.nginx.org/unit/:splat"
  status = 200
  headers = {X-From = "Netlify"}
