# keep our base image as small as possible
FROM nginx/unit:1.16.0-ruby2.5

# port used by the listener in config.json
EXPOSE 8080

# application setup
RUN mkdir /www/ && echo '                                                   \n\
require "digest"                                                            \n\
require "json"                                                              \n\
app = Proc.new do |env|                                                     \n\
    body = env["rack.input"].read                                           \n\
    r = {                                                                   \n\
        "message" => "Kirov reporting",                                     \n\
        "agent"   => "NGINX Unit 1.16.0",                                   \n\
        "body"    => body,                                                  \n\
        "headers" => env.select { |key, value| key.include?("HTTP_") },     \n\
        "sha256"  => Digest::SHA256.hexdigest(body)                         \n\
    }                                                                       \n\
                                                                            \n\
    ["200", {                                                               \n\
        "Content-Type" => "application/json; charset=utf-8",                \n\
    }, [JSON.pretty_generate(r)]]                                           \n\
end;                                                                        \n\
run app                                                                     \n\
' > /www/config.ru                                                            \
# prepare the app config for Unit
    && echo '{                                                                \
    "listeners": {                                                            \
        "*:8080": {                                                           \
            "pass": "applications/ruby_app"                                   \
        }                                                                     \
    },                                                                        \
    "applications": {                                                         \
        "ruby_app": {                                                         \
            "type": "ruby",                                                   \
            "working_directory": "/www/",                                     \
            "script": "config.ru"                                             \
        }                                                                     \
    }                                                                         \
    }' > /docker-entrypoint.d/config.json
