# keep our base image as small as possible
FROM nginx/unit:1.12.0-minimal

# port used by the listener in config.json
EXPOSE 8080

# add Perl language and corresponding language module
RUN apt update                                                             \
    && apt install -y apt-transport-https gnupg1                           \
    && curl https://nginx.org/keys/nginx_signing.key | apt-key add -       \
    && echo "deb https://packages.nginx.org/unit/debian/ stretch unit"     \
         > /etc/apt/sources.list.d/unit.list                               \
    && echo "deb-src https://packages.nginx.org/unit/debian/ stretch unit" \
         >> /etc/apt/sources.list.d/unit.list                              \
    && apt update                                                          \
    && apt install -y unit-perl                                            \
# final cleanup
    && apt remove -y apt-transport-https gnupg1                            \
    && apt autoremove --purge -y                                           \
    && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/*.list

#application setup
RUN mkdir /www/ && echo '                                                  \
    my $app = sub {                                                        \
        return [                                                           \
            "200",                                                         \
            [ "Content-Type" => "text/plain" ],                            \
            [ "Hello, Unit!" ],                                            \
        ]                                                                  \
    };                                                                     \
    ' > /www/app.psgi                                                      \
# prepare the app config for Unit
    && echo '{                                                             \
    "listeners": {                                                         \
        "*:8080": {                                                        \
            "pass": "applications/perl_app"                                \
        }                                                                  \
    },                                                                     \
    "applications": {                                                      \
        "perl_app": {                                                      \
            "type": "perl",                                                \
            "working_directory": "/www/",                                  \
            "script": "/www/app.psgi"                                      \
        }                                                                  \
    }                                                                      \
    }' > /docker-entrypoint.d/config.json
